.TH INTERSECT 1
.SH NAME
intersect  alphabetically sort common words in any number of files 
.SH SYNOPSIS
.B intersect
[\fR \fIFILENAME\fR]
[\fR \fI...\fR]
.SH DESCRIPTION
.B intersect 
reads in files from the commandline and takes matching words and 
displays them to the screen in alphabetical order.

